//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillionBankProject.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRegister", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertRegister(string name, string surname, string Tel, string Email, string address, string password, string password_question, string Password_qanswer, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRegister", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertRegisterAsync(string name, string surname, string Tel, string Email, string address, string password, string password_question, string Password_qanswer, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Login(string ID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LoginAsync(string ID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertAccount(string AccountType, string AccountName, string AccountNumber, string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertAccountAsync(string AccountType, string AccountName, string AccountNumber, string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DisplayAccount(string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> DisplayAccountAsync(string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountDropdown", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AccountDropdown(string customerID, string AccountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountDropdown", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AccountDropdownAsync(string customerID, string AccountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAmount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getAmount(string accountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getAmountAsync(string accountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateBalance(string accountID, string amount, string isTransfered);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateBalanceAsync(string accountID, string amount, string isTransfered);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isTransfered", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string isTransfered(string Source, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isTransfered", ReplyAction="*")]
        System.Threading.Tasks.Task<string> isTransferedAsync(string Source, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertTransaction(string source, string destination, string amount, string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertTransactionAsync(string source, string destination, string amount, string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uodateProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable uodateProfile(string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uodateProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> uodateProfileAsync(string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateProfile(string customerID, string name, string surname, string Tel, string Email, string address, string password, string password_question, string Password_qanswer, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateProfileAsync(string customerID, string name, string surname, string Tel, string Email, string address, string password, string password_question, string Password_qanswer, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForgotPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ForgotPassword(string customerEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForgotPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ForgotPasswordAsync(string customerEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdatePassword(string Email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdatePasswordAsync(string Email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DisplayTransaction(string accountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> DisplayTransactionAsync(string accountID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BillionBankProject.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BillionBankProject.ServiceReference1.ServiceSoap>, BillionBankProject.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string InsertRegister(string name, string surname, string Tel, string Email, string address, string password, string password_question, string Password_qanswer, string ID) {
            return base.Channel.InsertRegister(name, surname, Tel, Email, address, password, password_question, Password_qanswer, ID);
        }
        
        public System.Threading.Tasks.Task<string> InsertRegisterAsync(string name, string surname, string Tel, string Email, string address, string password, string password_question, string Password_qanswer, string ID) {
            return base.Channel.InsertRegisterAsync(name, surname, Tel, Email, address, password, password_question, Password_qanswer, ID);
        }
        
        public System.Data.DataTable Login(string ID, string Password) {
            return base.Channel.Login(ID, Password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LoginAsync(string ID, string Password) {
            return base.Channel.LoginAsync(ID, Password);
        }
        
        public string InsertAccount(string AccountType, string AccountName, string AccountNumber, string customerID) {
            return base.Channel.InsertAccount(AccountType, AccountName, AccountNumber, customerID);
        }
        
        public System.Threading.Tasks.Task<string> InsertAccountAsync(string AccountType, string AccountName, string AccountNumber, string customerID) {
            return base.Channel.InsertAccountAsync(AccountType, AccountName, AccountNumber, customerID);
        }
        
        public System.Data.DataTable DisplayAccount(string customerID) {
            return base.Channel.DisplayAccount(customerID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DisplayAccountAsync(string customerID) {
            return base.Channel.DisplayAccountAsync(customerID);
        }
        
        public System.Data.DataTable AccountDropdown(string customerID, string AccountType) {
            return base.Channel.AccountDropdown(customerID, AccountType);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AccountDropdownAsync(string customerID, string AccountType) {
            return base.Channel.AccountDropdownAsync(customerID, AccountType);
        }
        
        public string getAmount(string accountID) {
            return base.Channel.getAmount(accountID);
        }
        
        public System.Threading.Tasks.Task<string> getAmountAsync(string accountID) {
            return base.Channel.getAmountAsync(accountID);
        }
        
        public string UpdateBalance(string accountID, string amount, string isTransfered) {
            return base.Channel.UpdateBalance(accountID, amount, isTransfered);
        }
        
        public System.Threading.Tasks.Task<string> UpdateBalanceAsync(string accountID, string amount, string isTransfered) {
            return base.Channel.UpdateBalanceAsync(accountID, amount, isTransfered);
        }
        
        public string isTransfered(string Source, string destination) {
            return base.Channel.isTransfered(Source, destination);
        }
        
        public System.Threading.Tasks.Task<string> isTransferedAsync(string Source, string destination) {
            return base.Channel.isTransferedAsync(Source, destination);
        }
        
        public string InsertTransaction(string source, string destination, string amount, string customerID) {
            return base.Channel.InsertTransaction(source, destination, amount, customerID);
        }
        
        public System.Threading.Tasks.Task<string> InsertTransactionAsync(string source, string destination, string amount, string customerID) {
            return base.Channel.InsertTransactionAsync(source, destination, amount, customerID);
        }
        
        public System.Data.DataTable uodateProfile(string customerID) {
            return base.Channel.uodateProfile(customerID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> uodateProfileAsync(string customerID) {
            return base.Channel.uodateProfileAsync(customerID);
        }
        
        public string UpdateProfile(string customerID, string name, string surname, string Tel, string Email, string address, string password, string password_question, string Password_qanswer, string ID) {
            return base.Channel.UpdateProfile(customerID, name, surname, Tel, Email, address, password, password_question, Password_qanswer, ID);
        }
        
        public System.Threading.Tasks.Task<string> UpdateProfileAsync(string customerID, string name, string surname, string Tel, string Email, string address, string password, string password_question, string Password_qanswer, string ID) {
            return base.Channel.UpdateProfileAsync(customerID, name, surname, Tel, Email, address, password, password_question, Password_qanswer, ID);
        }
        
        public System.Data.DataTable ForgotPassword(string customerEmail) {
            return base.Channel.ForgotPassword(customerEmail);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ForgotPasswordAsync(string customerEmail) {
            return base.Channel.ForgotPasswordAsync(customerEmail);
        }
        
        public string UpdatePassword(string Email, string password) {
            return base.Channel.UpdatePassword(Email, password);
        }
        
        public System.Threading.Tasks.Task<string> UpdatePasswordAsync(string Email, string password) {
            return base.Channel.UpdatePasswordAsync(Email, password);
        }
        
        public System.Data.DataTable DisplayTransaction(string accountID) {
            return base.Channel.DisplayTransaction(accountID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DisplayTransactionAsync(string accountID) {
            return base.Channel.DisplayTransactionAsync(accountID);
        }
    }
}
